{100}{}{Estás viendo al Demonio Encargado.}
{101}{}{¿K´haces aquí?}
{102}{}{Buscando restos del pasado del futuro.}
{103}{}{Exploro.}
{104}{}{¿A ti qué te parece, cara gusano?}
{105}{}{Dug-duh.}
{106}{}{¡K´has dicho?}
{107}{}{Nada.}
{108}{}{Estoy buscando la tecnología perdida.}
{109}{}{Creí que habías dicho eso. Sal de mi queli.}
{110}{}{Oh, no por acá. A lo mejó en lo arto del templo
 o donde el agua. Hasta luego, cara huevo.}
{111}{}{¡Ack! No esplores mish movidash.
 ¡Aire! ¡Vamos!.}
{112}{}{No te comportes así con el titi. Yo llevo el cotarro.}
{113}{}{Oh, sí.}
{114}{}{Voy a coger ese careto tuyo y me lo voy a meter por el. . .}
{115}{}{¡Ack! Vale, acepto. Me voy.}
{116}{}{Quién coño eres tú pa´tratarme asín. ¡Sube y pedalea caaraculo!}
{117}{}{No quiero charlas contigo.}
