{100}{}{Cougar, assistant de Doc Morbide.}
{101}{}{Comment ça va?}
{102}{}{Bien, et toi?}
{103}{}{Je voudrais voir le Doc.}
{104}{}{Eurr.}
{105}{}{Le Cougar va toujours bien.}
{106}{}{Hé, je dois savoir. . .}
{107}{}{Va voir mon assistant, Flash, là-bas. Il t'aidera.}
{108}{}{Oh! Ne parle pas si vite, mec. Tu vas donner la migraine au Cougar. Parle plutôt à Flash.}
{109}{}{C'est encore toi. Le Cougar n'a plus rien à dire.}
{110}{}{Le Cougar te surveille!}
{111}{}{Beau matos, t'as récupéré ça tout seul?}
